[package]
name = "smartopen"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
clap = { version = "4.5", features = ["derive"] }
crossterm = "0.28"
directories = "6"
ratatui = "0.29"
serde = { version = "1", features = ["derive"] }
shellexpand = "3.1"
toml = "0.8"
similar = "3.1.1"
thiserror = "2.0.18"
toml_edit = "0.25.12"

[[bin]]
name = "smartopen"
path = "src/main.rs"

[[bin]]
name = "opn"
path = "src/main.rs"
