//! broot: open files with the same viewers, from the same spec, through the same menu.
//!
//! broot picks verbs by `apply_to` (file/dir/text), not by file type, so it cannot choose
//! mdfried-vs-doxx the way yazi's rules do. Instead one verb bound to Enter on files
//! runs a `case "$1" in …` dispatcher built from the spec's URL rules — each branch is
//! that opener's own run command, which already takes `"$@"`/`"$1"`, so it works
//! unchanged under `sh -c`. Directories keep broot's native Enter.
//!
//! The verb is written to `<broot-config>/smartopen.hjson` (valid JSON is valid Hjson)
//! and imported from `conf.hjson`. It also carries an `invocation`, so `:smartopen` in
//! broot's input triggers it too — which is how the navigator tests drive it.
//!
//! Ported from yazi-opener-config's `broot.rs`; the file name and generator note changed.

use std::fs;
use std::path::Path;

use anyhow::{Context, Result};

use crate::spec::{Matcher, Spec};
use crate::tomlio::{self, Outcome};

pub const OPENERS_FILE: &str = "smartopen.hjson";
/// The file yazi-opener-config wrote; replaced by ours and no longer imported.
const LEGACY_OPENERS_FILE: &str = "openers.hjson";

/// The contents of `smartopen.hjson` for this spec.
///
/// The verb runs in broot's own terminal: `leave_broot: false` has broot hand the screen
/// over for the command and take it back afterwards, the way its built-in `edit` verb
/// runs `$EDITOR`. The menu, and a viewer picked from it, appear where broot was. (It
/// used to `exec "$TERMINAL" -e …` with ghostty as the fallback — a new window on Linux,
/// and nothing at all on a Mac without ghostty.) A command that wants its own window
/// says so with `terminal = true`.
///
/// NO BRACES ANYWHERE IN THE VERB EXCEPT `{file}`. broot substitutes every `{name}` in a
/// verb's text with its own placeholders, and an unknown one becomes nothing: the
/// original `exec "${TERMINAL:-ghostty}"` reached the shell as `exec "$"`, and the
/// dispatcher's `${1##*/}` as `$`. The navigator test found both.
pub fn openers_hjson(spec: &Spec) -> String {
    let script = dispatch_script(spec);
    let external = json_array(&["sh", "-c", &script, "broot-open", "{file}"]);
    format!(
        "// Generated by smartopen — broot opens files with the same viewers as yazi.\n\
         // Regenerate with: smartopen broot apply\n\
         {{\n  \"verbs\": [\n    {{\n      \"invocation\": \"smartopen\",\n      \"key\": \"enter\",\n      \"apply_to\": \"file\",\n      \"external\": {external},\n      \"leave_broot\": false\n    }}\n  ]\n}}\n",
    )
}

/// Build `b=$(basename "$1"); case "$b" in (glob|glob) <run> ;; … (*) <default run> ;; esac`.
fn dispatch_script(spec: &Spec) -> String {
    let mut prelude = String::new();
    // Specific branches from URL rules, grouping consecutive rules with the same command.
    let mut branches: Vec<(Vec<String>, String)> = Vec::new();
    for rule in &spec.prepend_rules {
        let glob = match &rule.matcher {
            Matcher::Url(u) => u.clone(),
            Matcher::Mime(_) => continue, // broot matches on the path, not the mime type
        };
        let Some(run) = rule.use_openers.first().and_then(|n| run_for(spec, n)) else {
            continue;
        };
        let run = debrace(&run, &mut prelude);
        if let Some(last) = branches.last_mut()
            && last.1 == run
        {
            last.0.push(glob);
            continue;
        }
        branches.push((vec![glob], run));
    }

    // Default branch: a `mime = "*"` catch-all if present (the smartopen engine), else
    // the `edit` opener, else $EDITOR.
    let default_run = spec
        .prepend_rules
        .iter()
        .find(|r| matches!(&r.matcher, Matcher::Mime(m) if m == "*"))
        .and_then(|r| r.use_openers.first())
        .and_then(|n| run_for(spec, n))
        .or_else(|| run_for(spec, "edit"))
        .unwrap_or_else(|| "${EDITOR:-micro} \"$@\"".to_string());
    let default_run = debrace(&default_run, &mut prelude);

    // broot passes the full path; match the basename (like yazi's url globs) but run the
    // viewer on the full path ("$@"/"$1").
    let mut s = prelude;
    s.push_str("b=$(basename \"$1\"); case \"$b\" in ");
    for (globs, run) in &branches {
        s.push_str(&format!("({}) {} ;; ", globs.join("|"), run));
    }
    s.push_str(&format!("(*) {default_run} ;; esac"));
    s
}

/// Rewrite `${VAR:-default}` as `$VAR`, hoisting the default into `prelude` as
/// `[ -n "$VAR" ] || VAR=default; ` — broot would otherwise eat the braces.
fn debrace(run: &str, prelude: &mut String) -> String {
    let mut out = String::with_capacity(run.len());
    let mut rest = run;
    while let Some(start) = rest.find("${") {
        out.push_str(&rest[..start]);
        let after = &rest[start + 2..];
        let Some(end) = after.find('}') else {
            out.push_str(&rest[start..]);
            return out;
        };
        let inner = &after[..end];
        match inner.split_once(":-") {
            Some((var, default)) if !var.is_empty() => {
                let guard = format!("[ -n \"${var}\" ] || {var}={default}; ");
                if !prelude.contains(&guard) {
                    prelude.push_str(&guard);
                }
                out.push_str(&format!("${var}"));
            }
            _ => out.push_str(&format!("${inner}")),
        }
        rest = &after[end + 1..];
    }
    out.push_str(rest);
    out
}

fn run_for(spec: &Spec, opener: &str) -> Option<String> {
    spec.openers
        .iter()
        .find(|o| o.name == opener)
        .and_then(|o| o.runs.first())
        .map(|r| r.run.clone())
}

/// The full new `conf.hjson` text and whether the openers file would change — for
/// `diff` and `check`, without writing.
pub fn render(broot_dir: &Path, spec: &Spec) -> Result<(String, Option<String>)> {
    let openers = broot_dir.join(OPENERS_FILE);
    let new_openers = openers_hjson(spec);
    let existing = tomlio::read_optional(&openers)?;
    let openers_change = (existing.as_deref() != Some(new_openers.as_str())).then_some(new_openers);

    let conf = broot_dir.join("conf.hjson");
    let conf_text = tomlio::read_optional(&conf)?;
    let new_conf = match conf_text {
        None => format!("# created by smartopen\nimports: [\n    {OPENERS_FILE}\n]\n"),
        Some(text) if text.contains(OPENERS_FILE) => text,
        Some(text) => insert_into_imports(&text).unwrap_or_else(|| {
            let mut t = text;
            if !t.ends_with('\n') {
                t.push('\n');
            }
            t.push_str(&format!(
                "\nimports: [\n    {OPENERS_FILE}   # added by smartopen\n]\n"
            ));
            t
        }),
    };
    Ok((new_conf, openers_change))
}

/// Write `smartopen.hjson` into `broot_dir` and ensure `conf.hjson` imports it.
/// Returns (openers outcome, whether the import was added).
pub fn apply(
    broot_dir: &Path,
    spec: &Spec,
    no_import: bool,
    no_backup: bool,
) -> Result<(Outcome, bool)> {
    let openers = broot_dir.join(OPENERS_FILE);
    let new = openers_hjson(spec);

    let existing = tomlio::read_optional(&openers)?;
    let outcome = if existing.as_deref() == Some(new.as_str()) {
        Outcome::InSync
    } else {
        fs::create_dir_all(broot_dir)
            .with_context(|| format!("creating {}", broot_dir.display()))?;
        if existing.is_some() && !no_backup {
            tomlio::backup(&openers)?;
        }
        tomlio::atomic_write(&openers, &new)?;
        if existing.is_some() {
            Outcome::Updated
        } else {
            Outcome::Created
        }
    };

    let import_added = if no_import {
        false
    } else {
        ensure_import(&broot_dir.join("conf.hjson"), no_backup)?
    };
    Ok((outcome, import_added))
}

/// Make sure broot's `conf.hjson` imports the openers file. Returns true if it changed.
/// An import of the legacy `openers.hjson` is replaced rather than duplicated, so a
/// machine set up by yazi-opener-config does not end up with two Enter verbs.
fn ensure_import(conf: &Path, no_backup: bool) -> Result<bool> {
    if !conf.exists() {
        // broot keeps its built-in default verbs even with a minimal conf.
        let body = format!("# created by smartopen\nimports: [\n    {OPENERS_FILE}\n]\n");
        if let Some(p) = conf.parent() {
            fs::create_dir_all(p).ok();
        }
        tomlio::atomic_write(conf, &body)?;
        return Ok(true);
    }
    let text = fs::read_to_string(conf).with_context(|| format!("reading {}", conf.display()))?;
    if text.contains(OPENERS_FILE) {
        return Ok(false);
    }
    let out = if text.contains(LEGACY_OPENERS_FILE) {
        text.replace(LEGACY_OPENERS_FILE, OPENERS_FILE)
    } else {
        match insert_into_imports(&text) {
            Some(updated) => updated,
            None => {
                let mut t = text;
                if !t.ends_with('\n') {
                    t.push('\n');
                }
                t.push_str(&format!(
                    "\nimports: [\n    {OPENERS_FILE}   # added by smartopen\n]\n"
                ));
                t
            }
        }
    };
    if !no_backup {
        tomlio::backup(conf)?;
    }
    tomlio::atomic_write(conf, &out)?;
    Ok(true)
}

/// Insert our import as the first entry of an existing `imports: [ … ]` array.
fn insert_into_imports(text: &str) -> Option<String> {
    let key = text.find("imports:")?;
    let bracket = key + text[key..].find('[')?;
    let after = bracket + 1;
    // hjson quoteless strings run to end of line, so the comment must be on its own line
    // (an inline `# ...` after the filename would be swallowed into the import path).
    let mut out = String::with_capacity(text.len() + 48);
    out.push_str(&text[..after]);
    out.push_str(&format!("\n    # added by smartopen\n    {OPENERS_FILE}"));
    out.push_str(&text[after..]);
    Some(out)
}

/// A JSON array of strings, escaped the JSON way.
fn json_array(items: &[&str]) -> String {
    let parts: Vec<String> = items.iter().map(|s| json_string(s)).collect();
    format!("[{}]", parts.join(", "))
}

fn json_string(s: &str) -> String {
    let mut o = String::with_capacity(s.len() + 2);
    o.push('"');
    for c in s.chars() {
        match c {
            '"' => o.push_str("\\\""),
            '\\' => o.push_str("\\\\"),
            '\n' => o.push_str("\\n"),
            '\t' => o.push_str("\\t"),
            '\r' => o.push_str("\\r"),
            c if (c as u32) < 0x20 => o.push_str(&format!("\\u{:04x}", c as u32)),
            c => o.push(c),
        }
    }
    o.push('"');
    o
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::engine::{Engine, effective};

    fn temp_dir(tag: &str) -> std::path::PathBuf {
        let dir =
            std::env::temp_dir().join(format!("smartopen-broot-{tag}-{}", std::process::id()));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();
        dir
    }

    #[test]
    fn openers_file_is_valid_json_with_one_enter_verb_named_smartopen() {
        let text = openers_hjson(&Spec::builtin());
        let json: serde_json::Value = serde_json::from_str(
            &text
                .lines()
                .filter(|l| !l.starts_with("//"))
                .collect::<Vec<_>>()
                .join("\n"),
        )
        .expect("valid JSON is valid Hjson");
        let verb = &json["verbs"][0];
        assert_eq!(verb["key"], "enter");
        assert_eq!(verb["apply_to"], "file");
        assert_eq!(verb["invocation"], "smartopen");
        assert_eq!(verb["leave_broot"], false);
        assert_eq!(verb["external"][0], "sh");
        assert_eq!(
            verb["external"].as_array().unwrap().last().unwrap(),
            "{file}"
        );
        // In broot's terminal, like its `edit` verb: no terminal emulator is named.
        assert!(
            !text.contains("TERMINAL") && !text.contains("ghostty"),
            "{text}"
        );
    }

    #[test]
    fn dispatcher_groups_globs_and_falls_back_to_edit() {
        let script = dispatch_script(&Spec::builtin());
        assert!(
            script.starts_with(
                "[ -n \"$EDITOR\" ] || EDITOR=micro; b=$(basename \"$1\"); case \"$b\" in "
            ),
            "{script}"
        );
        assert!(
            script.contains("(*.md|*.markdown) mdfried \"$@\" ;;"),
            "{script}"
        );
        assert!(
            script.contains("(*.xlsx|*.xls) xleak -i \"$@\" ;;"),
            "{script}"
        );
        assert!(script.ends_with("(*) $EDITOR \"$@\" ;; esac"), "{script}");
    }

    #[test]
    fn nothing_in_the_verb_has_braces_except_the_file_placeholder() {
        for spec in [
            Spec::builtin(),
            effective(&Spec::builtin(), Engine::Smartopen, "smartopen"),
        ] {
            let text = openers_hjson(&spec);
            let braces = text.matches('{').count();
            // The JSON object, the verb object, and `{file}`: three opening braces.
            assert_eq!(braces, 3, "broot would eat these:\n{text}");
        }
    }

    #[test]
    fn debrace_hoists_defaults_into_a_prelude() {
        let mut prelude = String::new();
        let run = debrace("${EDITOR:-micro} \"$@\" ${PAGER:-less}", &mut prelude);
        assert_eq!(run, "$EDITOR \"$@\" $PAGER");
        assert_eq!(
            prelude,
            "[ -n \"$EDITOR\" ] || EDITOR=micro; [ -n \"$PAGER\" ] || PAGER=less; "
        );
        assert_eq!(debrace("plain \"$1\"", &mut String::new()), "plain \"$1\"");
    }

    #[test]
    fn smartopen_engine_dispatches_everything_to_the_binary() {
        let spec = effective(&Spec::builtin(), Engine::Smartopen, "opn");
        let script = dispatch_script(&spec);
        assert!(script.ends_with("(*) opn \"$@\" ;; esac"), "{script}");
    }

    #[test]
    fn apply_creates_files_then_reports_in_sync_and_replaces_the_legacy_import() {
        let dir = temp_dir("apply");
        let spec = Spec::builtin();

        let (outcome, added) = apply(&dir, &spec, false, true).unwrap();
        assert_eq!(outcome, Outcome::Created);
        assert!(added);
        assert!(dir.join(OPENERS_FILE).is_file());
        assert!(
            fs::read_to_string(dir.join("conf.hjson"))
                .unwrap()
                .contains(OPENERS_FILE)
        );

        let (outcome, added) = apply(&dir, &spec, false, true).unwrap();
        assert_eq!(outcome, Outcome::InSync);
        assert!(!added);

        // A conf written by yazi-opener-config imports openers.hjson; it gets replaced.
        fs::write(
            dir.join("conf.hjson"),
            "imports: [\n    openers.hjson\n]\nverbs: []\n",
        )
        .unwrap();
        let (_, added) = apply(&dir, &spec, false, true).unwrap();
        assert!(added);
        let conf = fs::read_to_string(dir.join("conf.hjson")).unwrap();
        assert!(
            conf.contains(OPENERS_FILE) && !conf.contains("openers.hjson"),
            "{conf}"
        );

        let _ = fs::remove_dir_all(dir);
    }

    #[test]
    fn import_is_inserted_first_in_an_existing_array_or_appended() {
        let existing = "verbs: []\nimports: [\n    other.hjson\n]\n";
        let updated = insert_into_imports(existing).unwrap();
        assert!(
            updated.contains(
                "imports: [\n    # added by smartopen\n    smartopen.hjson\n    other.hjson"
            ),
            "{updated}"
        );
        assert!(insert_into_imports("verbs: []\n").is_none());
    }

    #[test]
    fn render_reports_what_would_change_without_writing() {
        let dir = temp_dir("render");
        let (conf, openers) = render(&dir, &Spec::builtin()).unwrap();
        assert!(conf.contains(OPENERS_FILE));
        assert!(openers.is_some());
        assert!(!dir.join(OPENERS_FILE).exists(), "render must not write");
        let _ = fs::remove_dir_all(dir);
    }
}
