//! Render the association spec into a broot config so broot opens files with the same
//! viewers as yazi.
//!
//! broot selects verbs by `apply_to` (file/dir/text), not by extension, so it can't pick
//! mdfried-vs-doxx the way yazi's glob/mime rules do. Instead we emit a single verb bound
//! to Enter on files whose command is a `case "$1" in …` dispatcher built from the spec's
//! URL rules (each branch is that opener's own run command — which already uses `"$@"`/
//! `"$1"`, so it works unchanged under `sh -c`). Directories keep broot's native Enter.
//!
//! The verb is written to `<broot-config>/openers.hjson` (valid JSON is valid Hjson) and
//! imported from `conf.hjson`.

use std::fs;
use std::path::Path;

use anyhow::{Context, Result};

use crate::spec::{Matcher, Spec};
use crate::tomlio::{self, Outcome};

const OPENERS_FILE: &str = "openers.hjson";

/// The contents of `openers.hjson` for this spec.
pub fn openers_hjson(spec: &Spec) -> String {
    let script = dispatch_script(spec);
    let external = json_array(&["sh", "-c", &script, "broot-open", "{file}"]);
    format!(
        "// Generated by yazi-opener-config — broot opens files with the same viewers as yazi.\n\
         // Regenerate with: yazi-opener-config broot\n\
         {{\n  \"verbs\": [\n    {{\n      \"key\": \"enter\",\n      \"apply_to\": \"file\",\n      \"external\": {external},\n      \"leave_broot\": false\n    }}\n  ]\n}}\n",
    )
}

/// Build `case "$1" in (glob|glob) <run> ;; … (*) <default run> ;; esac` from the spec.
fn dispatch_script(spec: &Spec) -> String {
    // Specific branches from URL rules, grouping consecutive rules with the same command.
    let mut branches: Vec<(Vec<String>, String)> = Vec::new();
    for rule in &spec.prepend_rules {
        let glob = match &rule.matcher {
            Matcher::Url(u) => u.clone(),
            Matcher::Mime(_) => continue, // broot matches on the path, not the mime type
        };
        let Some(run) = rule.use_openers.first().and_then(|n| run_for(spec, n)) else { continue };
        if let Some(last) = branches.last_mut()
            && last.1 == run
        {
            last.0.push(glob);
            continue;
        }
        branches.push((vec![glob], run));
    }

    // Default branch: a `mime = "*"` catch-all if present (e.g. smartopen engine), else the
    // `edit` opener, else $EDITOR.
    let default_run = spec
        .prepend_rules
        .iter()
        .find(|r| matches!(&r.matcher, Matcher::Mime(m) if m == "*"))
        .and_then(|r| r.use_openers.first())
        .and_then(|n| run_for(spec, n))
        .or_else(|| run_for(spec, "edit"))
        .unwrap_or_else(|| "${EDITOR:-micro} \"$@\"".to_string());

    // broot passes the full path; match the basename (like yazi's url globs) but run the
    // viewer on the full path ("$@"/"$1").
    let mut s = String::from("b=\"${1##*/}\"; case \"$b\" in ");
    for (globs, run) in &branches {
        s.push_str(&format!("({}) {} ;; ", globs.join("|"), run));
    }
    s.push_str(&format!("(*) {default_run} ;; esac"));
    s
}

fn run_for(spec: &Spec, opener: &str) -> Option<String> {
    spec.openers
        .iter()
        .find(|o| o.name == opener)
        .and_then(|o| o.runs.first())
        .map(|r| r.run.clone())
}

/// Write `openers.hjson` into `broot_dir` and ensure `conf.hjson` imports it.
/// Returns (openers outcome, whether the import was added).
pub fn apply(broot_dir: &Path, spec: &Spec, no_import: bool, no_backup: bool) -> Result<(Outcome, bool)> {
    let openers = broot_dir.join(OPENERS_FILE);
    let new = openers_hjson(spec);

    let existing = tomlio::read_optional(&openers)?;
    let outcome = if existing.as_deref() == Some(new.as_str()) {
        Outcome::InSync
    } else {
        fs::create_dir_all(broot_dir).with_context(|| format!("creating {}", broot_dir.display()))?;
        if existing.is_some() && !no_backup {
            tomlio::backup(&openers)?;
        }
        tomlio::atomic_write(&openers, &new)?;
        if existing.is_some() { Outcome::Updated } else { Outcome::Created }
    };

    let import_added = if no_import { false } else { ensure_import(&broot_dir.join("conf.hjson"), no_backup)? };
    Ok((outcome, import_added))
}

/// Make sure broot's `conf.hjson` imports `openers.hjson`. Returns true if it changed.
fn ensure_import(conf: &Path, no_backup: bool) -> Result<bool> {
    if !conf.exists() {
        // broot keeps its built-in default verbs even with a minimal conf.
        let body = format!("# created by yazi-opener-config\nimports: [\n    {OPENERS_FILE}\n]\n");
        if let Some(p) = conf.parent() {
            fs::create_dir_all(p).ok();
        }
        tomlio::atomic_write(conf, &body)?;
        return Ok(true);
    }
    let text = fs::read_to_string(conf).with_context(|| format!("reading {}", conf.display()))?;
    if text.contains(OPENERS_FILE) {
        return Ok(false);
    }
    let out = match insert_into_imports(&text) {
        Some(updated) => updated,
        None => {
            let mut t = text;
            if !t.ends_with('\n') {
                t.push('\n');
            }
            t.push_str(&format!("\nimports: [\n    {OPENERS_FILE}   # added by yazi-opener-config\n]\n"));
            t
        }
    };
    if !no_backup {
        tomlio::backup(conf)?;
    }
    tomlio::atomic_write(conf, &out)?;
    Ok(true)
}

/// Insert our import as the first entry of an existing `imports: [ … ]` array.
fn insert_into_imports(text: &str) -> Option<String> {
    let key = text.find("imports:")?;
    let bracket = key + text[key..].find('[')?;
    let after = bracket + 1;
    // hjson quoteless strings run to end of line, so the comment must be on its own line
    // (an inline `# ...` after the filename would be swallowed into the import path).
    let mut out = String::with_capacity(text.len() + 48);
    out.push_str(&text[..after]);
    out.push_str(&format!("\n    # added by yazi-opener-config\n    {OPENERS_FILE}"));
    out.push_str(&text[after..]);
    Some(out)
}

// ---- JSON helpers (output is valid JSON, which broot accepts as Hjson) ----

fn json_escape(s: &str) -> String {
    let mut o = String::with_capacity(s.len() + 2);
    for c in s.chars() {
        match c {
            '"' => o.push_str("\\\""),
            '\\' => o.push_str("\\\\"),
            '\n' => o.push_str("\\n"),
            '\t' => o.push_str("\\t"),
            '\r' => o.push_str("\\r"),
            c if (c as u32) < 0x20 => o.push_str(&format!("\\u{:04x}", c as u32)),
            c => o.push(c),
        }
    }
    o
}

fn json_array(items: &[&str]) -> String {
    let inner: Vec<String> = items.iter().map(|i| format!("\"{}\"", json_escape(i))).collect();
    format!("[{}]", inner.join(", "))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::engine::{self, Engine};

    #[test]
    fn dispatch_covers_the_yazi_viewers() {
        let s = dispatch_script(&Spec::builtin());
        for needle in [
            "b=\"${1##*/}\"; case \"$b\" in",
            "(*.md|*.markdown) mdfried",
            "(*.docx) doxx",
            "(*.xlsx|*.xls) xleak -i",
            "(*.csv) xan view -p -A",
            "lazyenv",
            "(*.html|*.htm) chromium",
            "(*) ${EDITOR:-micro}",
            "esac",
        ] {
            assert!(s.contains(needle), "dispatch script missing: {needle}\n{s}");
        }
    }

    #[test]
    fn env_globs_are_grouped() {
        let s = dispatch_script(&Spec::builtin());
        assert!(s.contains("(.env|.env.*|*.env) lazyenv"), "{s}");
    }

    #[test]
    fn smartopen_engine_routes_all_to_smartopen() {
        let spec = engine::effective(&Spec::builtin(), Engine::Smartopen, "smartopen");
        let s = dispatch_script(&spec);
        assert!(s.contains("(*) smartopen \"$@\" ;; esac"), "{s}");
    }

    #[test]
    fn openers_file_has_enter_verb() {
        let h = openers_hjson(&Spec::builtin());
        assert!(h.contains("\"key\": \"enter\""));
        assert!(h.contains("\"apply_to\": \"file\""));
        assert!(h.contains("\"external\":"));
        assert!(h.contains("{file}"));
    }

    #[test]
    fn insert_into_imports_adds_first_entry() {
        let conf = "imports: [\n    verbs.hjson\n]\n";
        let out = insert_into_imports(conf).unwrap();
        assert!(out.contains(OPENERS_FILE));
        assert!(out.find(OPENERS_FILE).unwrap() < out.find("verbs.hjson").unwrap());
    }
}
