//! `smartopen shell <zsh|bash|fish>`: a keybinding that pastes the picked command onto
//! the prompt line instead of running it.
//!
//! Ctrl-G opens the picker; the choice lands in the line editor, unexecuted, so it can be
//! edited first and lands in history afterwards. This is what every launcher's users
//! reach for first. The snippets are generated rather than shipped as files so the
//! binary name in them is whichever one produced them — `opn shell zsh` binds `opn`.

use clap::ValueEnum;

#[derive(Clone, Copy, Debug, PartialEq, Eq, ValueEnum)]
pub enum ShellKind {
    Zsh,
    Bash,
    Fish,
}

pub fn snippet(kind: ShellKind, bin: &str) -> String {
    match kind {
        ShellKind::Zsh => format!(
            r#"# {bin}: Ctrl-G opens the launcher and puts the chosen command on the prompt line.
# Generated by `{bin} shell zsh`; source this from ~/.zshrc.
_{bin}_widget() {{
  local cmd
  cmd="$({bin} --print </dev/tty)" || {{ zle reset-prompt; return; }}
  if [[ -n "$cmd" ]]; then
    BUFFER="$cmd"
    CURSOR=${{#BUFFER}}
  fi
  zle reset-prompt
}}
zle -N _{bin}_widget
bindkey '^G' _{bin}_widget
"#
        ),
        ShellKind::Bash => format!(
            r#"# {bin}: Ctrl-G opens the launcher and puts the chosen command on the prompt line.
# Generated by `{bin} shell bash`; source this from ~/.bashrc.
_{bin}_widget() {{
  local cmd
  cmd="$({bin} --print </dev/tty)" || return
  [[ -n "$cmd" ]] || return
  READLINE_LINE="$cmd"
  READLINE_POINT=${{#READLINE_LINE}}
}}
bind -x '"\C-g": _{bin}_widget'
"#
        ),
        ShellKind::Fish => format!(
            r#"# {bin}: Ctrl-G opens the launcher and puts the chosen command on the prompt line.
# Generated by `{bin} shell fish`; source this from ~/.config/fish/config.fish.
function _{bin}_widget
    set -l cmd ({bin} --print </dev/tty)
    if test -n "$cmd"
        commandline -r -- "$cmd"
    end
    commandline -f repaint
end
bind \cg _{bin}_widget
"#
        ),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_snippet_binds_ctrl_g_to_the_named_binary() {
        for kind in [ShellKind::Zsh, ShellKind::Bash, ShellKind::Fish] {
            let text = snippet(kind, "opn");
            assert!(text.contains("opn --print"), "{kind:?}");
            assert!(text.contains("_opn_widget"), "{kind:?}");
            assert!(
                !text.contains("smartopen"),
                "{kind:?}: must name the binary invoked"
            );
        }
        assert!(snippet(ShellKind::Zsh, "smartopen").contains("bindkey '^G'"));
        assert!(snippet(ShellKind::Bash, "smartopen").contains(r#"bind -x '"\C-g"#));
        assert!(snippet(ShellKind::Fish, "smartopen").contains("bind \\cg"));
    }
}
